"""Initial migration with all models

Revision ID: aeff0cd58530
Revises: 
Create Date: 2025-11-15 20:03:06.719131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeff0cd58530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_sessions')
    op.drop_index('idx_agent_messages_session_time', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('idx_messages_agent_type', table_name='fastapi_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_messages_agent_type', 'fastapi_messages', ['agent_type'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], name='agent_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agent_messages_pkey')
    )
    op.create_index('idx_agent_messages_session_time', 'agent_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id', name='agent_sessions_pkey')
    )
    # ### end Alembic commands ###
